### ISSUE TITLE
Broken lol

### ISSUE THREAD

**Issue by SleekZ** [Lemons1337/Krunker-ESP#1]

**Comment by Lemons1337** [comment]
Patched after update and I’m too lazy to update this repo

**Comment by MrSleekZ** [comment]
Aye, don't blame ya.

**Comment by Lemons1337** [comment]
My personal cheat works but people like Mr CoderN just skid them so i stoped releasing my code

**Comment by MrSleekZ** [comment]
Plus releasing code to the public makes it 10000000 times more likely to get patched.
